name: Create Deployment Package

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP Package
        run: |
          zip -r deployment-package.zip sas-programs/

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sas-deployment-package
          path: deployment-package.zip
