name: SAS Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify SAS Files Exist
        run: |
          ls sas-programs
